### ISSUE TITLE
Tor daemon not running error

### ISSUE THREAD

**Issue by JustOneTry** [ruped24/tor_ip_switcher#4]
My tor service is running,i dont understand problem

**Comment by ruped24** [comment]
> My tor service is running,i dont understand problem

Try running:
 sudo python tips_setup.py "password"

**Comment by AZ3FU4D** [comment]
everytime i run ip switcher , i get daemon not running error while tor service running. what can i do?

**Comment by ruped24** [comment]
1. Make sure the control port is setup.
2. Get a new copy of the torrc file https://github.com/torproject/tor/blob/ac44e70ffc047941d196596dd651019c054b7faf/src/config/torrc.sample.in#L60
3. Then run these steps: https://github.com/ruped24/tor_ip_switcher/releases/tag/v2.7

Note. As of this week. Tor's end point is experiencing an overload.
You may experience very long latency. https://gitlab.torproject.org/tpo/tpa/team/-/issues/40842

**Comment by AZ3FU4D** [comment]
> 1. Make sure the control port is setup.
> 2. Get a new copy of the [torrc](https://github.com/torproject/tor/blob/ac44e70ffc047941d196596dd651019c054b7faf/src/config/torrc.sample.in) file.
> 3. https://github.com/torproject/tor/blob/ac44e70ffc047941d196596dd651019c054b7faf/src/config/torrc.sample.in#L57
> 4.  https://github.com/torproject/tor/blob/ac44e70ffc047941d196596dd651019c054b7faf/src/config/torrc.sample.in#L60
> 5. Then run these steps: https://github.com/ruped24/tor_ip_switcher/releases/tag/v2.7
> 
> Note. As of this week. [Tor's end point is experiencing an overload](https://gitlab.torproject.org/tpo/tpa/team/-/issues/40842).
> You may experience very long latency. 

Fixed. Thanks so much. Problem was on torrc file
