### ISSUE TITLE
its giving a syntaxerror

### ISSUE THREAD

**Issue by AnonymousNewbie777** [ruped24/tor_ip_switcher#9]
when i entered a command "python3 tor_ip_switcher.py" it is showing an error 
"
  File "/root/tor_ip_switcher/tor_ip_switcher.py", line 128
    except Exception, ex:
           ^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
"

may be you should recheck the program.

**Comment by AnonymousNewbie777** [comment]
> when i entered a command "python3 tor_ip_switcher.py" it is showing an error " File "/root/tor_ip_switcher/tor_ip_switcher.py", line 128 except Exception, ex: ^^^^^^^^^^^^^ SyntaxError: multiple exception types must be parenthesized "
> 
> may be you should recheck the program.

now when i resolve that issue for myself by correcting the program, and when i re-entered the command, it is giving me a Traceback i.e., "Traceback (most recent call last):
  File "/root/tor_ip_switcher/tor_ip_switcher.py", line 8, in <module>
    from commands import getoutput
ModuleNotFoundError: No module named 'commands' "

so please do something...

**Comment by ruped24** [comment]
> when i entered a command "python3 tor_ip_switcher.py" it is showing an error "

1) It's written in Python2. enter the command with python2.
2) Or just use the [AppImage](https://github.com/ruped24/tor_ip_switcher/releases/tag/v2.7), no python needed. Works on Linux.
3) There won't be any upgrade Python3 version.  Hence the AppImage.
